name: Deploy Next.js site to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  generate-static-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-nextjs
        with:
          tagManagerId: ${{ secrets.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_PROPERTY_ID }}
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./out

  deploy-static-site-to-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate-static-site
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
